# Below command builds the project and generates the output executable file.
# The name of the executable file is main.out by default. 
# If you want a different name, you can run the build command with a different name provided for the -o flag.
go build -o proteus
if test -f proteus; then
    echo "Project built successfully."
    # Below command runs the executable file generated by the build command.
    ./proteus
else
    echo "Project build was not successful :: Output binary file not generated."
fi
